name: "bluebell"
mode: "dev"
port: 8080
version: "v0.0.1"
start_time : "2025-05-01"
machine_id : 1

cors:
  allow_origins:
    - "http://47.115.56.249:8081"  # 你的前端地址
    - "http://localhost:5173"       # 开发环境地址
  allow_methods:
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
    - "OPTIONS"
  allow_headers:
    - "Content-Type"
    - "Authorization"
  allow_credentials: true
  max_age: 12


auth:
 jwt_access_expire: 6000 #8760
 jwt_refresh_expire: 6000 #8760
log:
  level: "debug"
  filename: "web_app.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root"
  dbname: "bluebell"
  max_open_conns: 200
  max_idle_conns: 500

redis:
  host: "127.0.0.1"
  port: 6379
  db: 0
  pool_size: 100
  password: ""